spring:
  profiles:
    active: dev
    group:
      dev: dev, common, secret-dev
      minseok: minseok-server, common, secret-prod
      mina: mina-server, common, secret-prod
      hyeok: hyeok-server, common, secret-prod

---

spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: minseok-server

domain:
  name:
    http: http://rasche.store
    https: https://rasche.store

app:
  cors:
    allowed-origins:
      - "http://rasche.store"
---
config:
  activate:
    on-profile: mina-server

domain:
  name:
    http: http://mina127.store
    https: https://mina127.store

app:
  cors:
    allowed-origins:
      - "http://mina127.store"
---

config:
  activate:
    on-profile: hyeok-server

domain:
  name:
    http: http://koyeh.store
    https: https://koyeh.store

app:
  cors:
    allowed-origins:
      - "http://koyeh.store"
---

server:
  port: 8080

spring:
  application:
    name: trip-planner
  config:
    activate:
      on-profile: common

# 스웨거 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  packages-to-scan: com.korit.trip_planner_back.controller

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.korit.trip_planner_back.entity