spring:
  profiles:
    active: dev
    group:
      dev: dev, common, secret
      minseok: minseok-server, common, secret

---
spring:
  config:
    activate:
      on-profile: dev


---
spring:
  config:
    activate:
      on-profile: minseok-server

domain:
  name:
    http: http://localhost:80
    https: https://localhost:443

app:
  cors:
    allowed-origins:
      - "http://localhost"
---

server:
  port: 8080

spring:
  application:
    name: trip-planner
  config:
    activate:
      on-profile: common

# 스웨거 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  packages-to-scan: com.korit.trip_planner_back.controller

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.korit.trip_planner_back.entity