name: GCP-VM-CICD

on:
  push:
    branches: [deploy-minseok, deploy-hyeok, deploy-mina, deploy-sungeun]
  pull_request:
    branches: [deploy-minseok, deploy-hyeok, deploy-mina, deploy-sungeun]

jobs:
  build-deplot-minseok:
    runs-on: ubuntu-22.04
    steps:
      - name: "환경변수 세팅"
        run: |
          if [ ${{github.ref}} == 'refs/heads/deploy-minseok' ]; then
          
            echo "GCP_VM_HOST=${{secrets.GCP_VM_HOST_MINSEOK}}" >> $GITHUB_ENV
            echo "GCP_VM_USERNAME=${{secrets.GCP_VM_USERNAME_MINSEOK}}" >> $GITHUB_ENV
            echo "GCP_VM_SSHKEY<<EOF" >> $GITHUB_ENV
            echo "${{secrets.GCP_VM_SSHKEY_MINSEOK}}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME_MINSEOK}}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD_MINSEOK}}" >> $GITHUB_ENV
            echo "APPLICATION_SECRET=${{secrets.APPLICATION_SECRET_MINSEOK}}" >> $GITHUB_ENV
            echo "REACT_ENV=${{secrets.REACT_ENV_MINSEOK}}" >> $GITHUB_ENV
            echo "ACTIVE_PROFILE=minseok" >> $GITHUB_ENV
  
          elif [ ${{github.ref}} == 'refs/heads/deploy-mina' ]; then
          
            echo "GCP_VM_HOST=${{secrets.GCP_VM_HOST_MINA}}" >> $GITHUB_ENV
            echo "GCP_VM_USERNAME=${{secrets.GCP_VM_USERNAME_MINA}}" >> $GITHUB_ENV
            echo "GCP_VM_SSHKEY<<EOF" >> $GITHUB_ENV
            echo "${{secrets.GCP_VM_SSHKEY_MINA}}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME_MINA}}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD_MINA}}" >> $GITHUB_ENV
            echo "APPLICATION_SECRET=${{secrets.APPLICATION_SECRET_MINA}}" >> $GITHUB_ENV
            echo "REACT_ENV=${{secrets.REACT_ENV_MINA}}" >> $GITHUB_ENV
            echo "ACTIVE_PROFILE=mina" >> $GITHUB_ENV
  
          elif [ ${{github.ref}} == 'refs/heads/deploy-hyeok' ]; then
          
            echo "GCP_VM_HOST=${{secrets.GCP_VM_HOST_HYEOK}}" >> $GITHUB_ENV
            echo "GCP_VM_USERNAME=${{secrets.GCP_VM_USERNAME_HYEOK}}" >> $GITHUB_ENV
            echo "GCP_VM_SSHKEY<<EOF" >> $GITHUB_ENV
            echo "${{secrets.GCP_VM_SSHKEY_HYEOK}}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME_HYEOK}}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD_HYEOK}}" >> $GITHUB_ENV
            echo "APPLICATION_SECRET=${{secrets.APPLICATION_SECRET_HYEOK}}" >> $GITHUB_ENV
            echo "REACT_ENV=${{secrets.REACT_ENV_HYEOK}}" >> $GITHUB_ENV
            echo "ACTIVE_PROFILE=hyeok" >> $GITHUB_ENV
            
          elif [ ${{github.ref}} == 'refs/heads/deploy-sungeun' ]; then
          
            echo "GCP_VM_HOST=${{secrets.GCP_VM_HOST_SUNGEUN}}" >> $GITHUB_ENV
            echo "GCP_VM_USERNAME=${{secrets.GCP_VM_USERNAME_SUNGEUN}}" >> $GITHUB_ENV
            echo "GCP_VM_SSHKEY<<EOF" >> $GITHUB_ENV
            echo "${{secrets.GCP_VM_SSHKEY_SUNGEUN}}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME_SUNGEUN}}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD_SUNGEUN}}" >> $GITHUB_ENV
            echo "APPLICATION_SECRET=${{secrets.APPLICATION_SECRET_SUNGEUN}}" >> $GITHUB_ENV
            echo "REACT_ENV=${{secrets.REACT_ENV_SUNGEUN}}" >> $GITHUB_ENV
            echo "ACTIVE_PROFILE=sungeun" >> $GITHUB_ENV
            
          fi
      - name: checkout
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{github.ref}}

      - name: install JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '21'
          distribution: 'temurin'
  
      - name: Springboot Build
        run: |
          cd trip_planner_back
          echo ${{env.APPLICATION_SECRET}} | base64 --decode > ./src/main/resources/application-secret-prod.yml
          chmod 777 ./mvnw
          ./mvnw clean package -Dtestskip -Dactive.profile=${{env.ACTIVE_PROFILE}}

      - name: Springboot Docker image build
        run: |
          cd trip_planner_back
          docker build -t ${{env.DOCKER_USERNAME}}/springboot-app:latest .

      - name: Springboot Docker image push
        run: |
          echo "${{env.DOCKER_PASSWORD}}" | docker login -u ${{env.DOCKER_USERNAME}} --password-stdin
          docker push ${{env.DOCKER_USERNAME}}/springboot-app:latest

      - name: React Docker image build
        run: |
          cd trip_planner_front
          echo ${{env.REACT_ENV}} | base64 --decode > .env
          docker build --no-cache -t ${{env.DOCKER_USERNAME}}/react-app:latest .

      - name: React Docker image push
        run: |
          docker push ${{env.DOCKER_USERNAME}}/react-app:latest

      - name: GCP SSH REMOTE
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.GCP_VM_HOST}}
          username: ${{env.GCP_VM_USERNAME}}
          key: ${{env.GCP_VM_SSHKEY}}
          script: |
            cd /home/${{env.GCP_VM_USERNAME}}
            sudo docker compose -f front-compose.yml pull
            sudo docker compose -f back-compose.yml pull
            sudo docker compose -f front-compose.yml down
            sudo docker compose -f front-compose.yml up -d
            sudo docker compose -f back-compose.yml down
            sudo docker compose -f back-compose.yml up -d
